### PR TITLE
Topic/add support for nested structs

### PR DESCRIPTION
**Pull request by wuerges**
Hello, would you consider merging my pull request?

Enabling the `full` feature of `syn` lets you use macros inside of the factories. Then you can use `create!` inside `create!`.

### CODE REVIEW

**Comment by GriffinHeart** [comment]
Oh hi @wuerges , apologies for the delay I probably missed the notifications about this PR :bow:

Interesting, in other projects I've used `factori` in we could definitely do this and its for sure a desirable feature.

I wonder if its because we end up importing `syn` with full feature from some other path. Let me just check when the week starts how its working over there, but in general yeah this is a good PR! :+1:

**Comment by wuerges** [comment]
Same thing happened in our project!

Em sáb., 28 de set. de 2024, 04:41, Hugo Almeida ***@***.***>
escreveu:

**Comment by GriffinHeart** [comment]
@wuerges yup, just confirmed on some other projects, let me add some extra examples to this and I'll merge it :)

**Comment by wuerges** [comment]
Awesome, thank you so much!

Em seg., 30 de set. de 2024, 08:24, Hugo Almeida ***@***.***>
escreveu:

**Comment by GriffinHeart** [comment]
@wuerges Thank you for your contribution :+1:

**Comment by GriffinHeart** [comment]
I've published this in v0.9.3 https://crates.io/crates/factori-imp

**Pull request merged**
